=== k-int/metadata/inventory-storage/ramls/schema/item.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "instance_id": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "barcode": {
      "type": "string"
    }
  },
  "required": [
    "instance_id",
    "barcode"
  ]
}

=== k-int/metadata/inventory-storage/ramls/examples/items_get.json
[
  {
    "id": "cd28da0f-a3e4-465c-82f1-acade4e8e170",
    "instance_id": "cd28da0f-a3e4-465c-82f1-acade4e8e170",
    "title": "Nod",
    "barcode": "456743454532"
  },
  {
    "id": "cd28da0f-a3e4-465c-82f1-acade4e8e170",
    "instance_id": "cd28da0f-a3e4-465c-82f1-acade4e8e170",
    "title": "Uprooted",
    "barcode": "645398607547"
  }
]
